version: 1
disable_existing_loggers: false

formatters:
  default:
    "()": "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)s [%(asctime)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    formatter: default
    filename: app.log
    encoding: utf8

loggers:
  uvicorn:
    handlers: [default, file]
    level: INFO
    propagate: false

  uvicorn.error:
    handlers: [default, file]
    level: INFO
    propagate: false

  uvicorn.access:
    handlers: [default, file]
    level: INFO
    propagate: false

root:
  handlers: [default, file]
  level: INFO
  propagate: false
